'use client';
import type { Metadata } from 'next';
import { useContext } from 'react';
import { Inter, Montserrat, Roboto_Condensed } from 'next/font/google';
import { FontThemeContext, FontThemeProvider } from '@/contexts/FontTheme';
import { fontClases, availableFont } from '@/constants/fontConstants';
import Navbar from '@/ui/Navbar';
import Footer from '@/ui/Footer';

import './globals.css';
import ColorThemeProvider from '@/contexts/ColorTheme';

const inter = Roboto_Condensed({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

const AppBody = ({ children }: { children: React.ReactNode }) => {
  const { currentFont } = useContext(FontThemeContext);

  return (
    <body className={`${fontClases[currentFont as availableFont]}`}>
      <ColorThemeProvider>
        <Navbar />
        {children}
        <Footer />
      </ColorThemeProvider>
    </body>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <FontThemeProvider>
        <AppBody>{children}</AppBody>
      </FontThemeProvider>
    </html>
  );
}
