import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from '@/ui/Navbar';
import Footer from '@/ui/Footer';

import './globals.css';
import ColorThemeProvider from '@/contexts/ColorTheme';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ColorThemeProvider>
          <Navbar />
          {children}
          <Footer />
        </ColorThemeProvider>
      </body>
    </html>
  );
}
